ruby/bootcamp/config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users
  root 'home#index', as: :home
end

ruby/bootcamp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/bootcamp/app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  has_one_attached :file
end

ruby/bootcamp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images
end

ruby/bootcamp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

ruby/bootcamp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
  end
end

ruby/bootcamp/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  def index
    # @images = Image.all
    @images = current_user.images
  end

  def show; end

  def new
    @image = Image.new
  end

  def edit; end

  def create
    if ImageService.create(image_params)
      redirect_to action: 'index'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if ImageService.update(image_params)
      redirect_to action: 'index'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @image.destroy

    redirect_to images_url, notice: 'Imagem deletada!'
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:title, :file, :user_id)
  end
end

ruby/bootcamp/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

ruby/bootcamp/app/helpers/home_helper.rb
module HomeHelper
end

ruby/bootcamp/app/helpers/images_helper.rb
module ImagesHelper
end

ruby/bootcamp/app/views/home/_login_modal.html.erb
<%= render 'modal_form', modal_id: 'login_modal', render_resource: 'devise/shared/login' %>

ruby/bootcamp/app/views/home/_modal_form.html.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Entrar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render render_resource %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

ruby/bootcamp/app/views/home/_sign_up_modal.html.erb
<%= render 'modal_form', modal_id: 'sign_up_modal', render_resource: 'devise/shared/sign_up' %>

ruby/bootcamp/app/views/home/index.html.erb
<div class="card mx-auto" style="width: 40%; min-width: 200px; margin-top: 10%">
  <div class="card-header">
    <% if user_signed_in? %>
      <i class="bi-card-text"></i> Home
    <% else %>
      <i class="bi-box-arrow-in-right"></i> Login
    <% end %>
  </div>
  
  <div class="card-body">
    <h5 class="card-title">Bem Vindo!</h5>
    <% if user_signed_in? %>
      <p class="card-text">Seja bem vindo ao meu site :D</p>
      <p class="card-text">Escolha uma das ações a serem feitas:</p>
      <div class="btn-group d-flex" role="group">
        <%= link_to 'Upload de Imagens', images_path, :class => 'btn btn-primary' %>
      </div>
    <% else %>
      <p class="card-text">Seja bem vindo ao meu site :D</p>
      <p class="card-text">Por favor, faça login ou se cadastre:</p>
      <div class="btn-group d-flex" role="group">
        <%= button_tag 'Entrar', class: 'btn btn-primary', data: { toggle: 'modal', target: '#login_modal' } %>
        <%= button_tag 'Criar conta', class: 'btn btn-secondary', data: { toggle: 'modal', target: '#sign_up_modal' } %>
      </div>
    <% end %>
  </div>
</div>


<%= render 'login_modal' %>
<%= render 'sign_up_modal' %>

ruby/bootcamp/app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field(:user_id, value: current_user.id) %>

  <div class="form-group">
    <%= form.label :title, 'Título', class: 'form-label' %>
    <%= form.text_field :title, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <div class="custom-file">
      <%= form.file_field :file, required: true, class: 'custom-file-input' %>
      <%= form.label :file, 'Escolha o arquivo...', class: 'custom-file-label' %>
      <div class="invalid-feedback">Example invalid custom file feedback</div>
    </div>
  </div>

  <div class="btn-group d-flex">
    <%= form.submit 'Enviar', class: 'btn btn-success' %>
  </div>
<% end %>

ruby/bootcamp/app/views/images/edit.html.erb
<div>
  <h1 class="text-center">Editar imagem</h1>

  <%= render 'form', image: @image %>

  <hr>

  <div class="btn-group">
    <%= link_to 'Detalhes', @image, class: 'btn btn-primary' %>
    <%= link_to 'Voltar', images_path, class: 'btn btn-secondary' %>
  </div>
</div>

ruby/bootcamp/app/views/images/index.html.erb
<div>
  <h1 class="text-center">Images</h1>

  <table class="table table-striped">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Título</th>
      <th scope="col">Imagem</th>
      <th scope="col">Ações</th>
    </tr>
    </thead>

    <tbody>
    <% @images.each do |image| %>
      <tr>
        <th scope="row"><%= image.title %></th>
        <td><%= image_tag url_for image.file.representation(resize_to_limit: [52, 52]) %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Detalhes', image, class: 'btn btn-primary' %>
            <%= link_to 'Editar', edit_image_path(image), class: 'btn btn-warning' %>
            <%= link_to 'Deletar', image, method: :delete, data: { confirm: 'Certeza?' }, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <hr>

  <%= link_to 'Nova imagem', new_image_path, class: 'btn btn-primary float-right' %>
</div>

ruby/bootcamp/app/views/images/new.html.erb
<div>
  <h1 class="text-center">Nova Imagem</h1>
  <%= render 'form', image: @image %>

  <hr>

  <%= link_to 'Voltar', images_path, class: 'btn btn-secondary' %>
</div>

ruby/bootcamp/app/views/images/show.html.erb
<div class="card mx-auto" style="width: 50%; min-width: 200px; margin-top: 1em; background-color: <%= @image.background_color %>">
  <%= image_tag @image.file, class: 'card-img-top' %>

  <div class="card-body">
    <h2 class="card-title" style="color: <%= @image.detail_color %>"><%= @image.title %>!</h5>
    <p class="card-text" style="color: <%= @image.primary_color %>">Primary color</p>
    <p class="card-text" style="color: <%= @image.secondary_color %>">Secondary color</p>
    <div class="btn-group d-flex">
      <%= link_to 'Editar', edit_image_path(@image), class: 'btn btn-warning' %>
      <%= link_to 'Voltar', images_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

ruby/bootcamp/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'PastaDoProjeto', home_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', home_path, class: 'nav-link' + (current_page?(home_path) ? ' active': '') %>
      </li>
    </ul>
  </div>
  
  <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
    <% if user_signed_in? %>
      <li class="navbar-text">
        Acessando como <strong><%= current_user.email %></strong>
      </li>

      <li class="nav-item">
        <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'nav-link' + (current_page?(edit_user_registration_path) ? ' active' : '') %>
      </li>

      <li class="nav-item">
        <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'nav-link' + (current_page?(destroy_user_session_path) ? ' active' : '')  %>
      </li>

    <% else %>

      <li class="nav-item">
        <%= link_to "Cadastrar", new_user_registration_path, :class => 'nav-link' + (current_page?(new_user_registration_path) ? ' active' : '')  %>
      </li>

      <li class="nav-item">
        <%= link_to "Entrar", new_user_session_path, :class => 'nav-link' + (current_page?(new_user_session_path) ? ' active' : '')  %>
      </li>
    <% end %>
  </ul>
</nav>

ruby/bootcamp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootcamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>